### ISSUE TITLE
New discovery-swarm-webrtc

### ISSUE THREAD

**Issue by tinchoz49** [geut/discovery-swarm-webrtc#5]
Hi everyone,

So, we were working on a web app on top of Dat and WebRTC using this module.

During this time we experiment different issues related with the transport layer:

- signalhubws
  1. Missing reconnection support in 
  2. Random crashes trying to send ACK
- webrtc-swarm
  1. Multiple connection open / connection closed

We thought that it was completely fault of WebRTC but we did an experiment using just simple-peer and simple-signal and we got establishing a connection for 3 hours without any issue. Also we try reconnection feature and it works, because the signal use socket.io so, we don't need to worry about this things.

We need to find a way to convert dicovery-swarm-webrtc in a easy way tool that helps us to connect hypercore, hyperdrive, etc

I started a [new branch](https://github.com/geut/discovery-swarm-webrtc/tree/new-webrtc-swarm) where I've been working with some ideas trying to use simple-peer and simple-signal. There is a lot of things to do but we can discuss everything here :smile: 

Progress:
- [x] Signal server that support multiple channels (topics to join it)
- [x] Refactory to use simple-signal to find peers and connect it to them
- [x] Support to stream option
- [x] Reconnection support for simple-peer connections. 
- [x] Support for multiple sockets url.
- [x] `Close` and `Destroy` methods.
- [x] `Leave` method
- [x] Url fallback 
- [ ] Better lookup using @RangerMauve idea of the [https://en.wikipedia.org/wiki/Minimum_spanning_tree](Minimum_spanning_tree)
- [ ] Testing

**Reconnection support for simple-peer connections**

I don't like how a solve this. When you lost a connection it always try to connect to the same peer, I think that if you are in a swarm you can lookup new connections instead and find another peer offering the same resource than the lost one.

**Support for multiple sockets url**

I think that this mechanism is complicated and is going to gives us more issues than solutions. 

Maybe we can find another way:

- Unique url to connect to and having multiple fallbacks url. The signal server can provide us the fallbacks url automatically.
- Create an adapter for socket io using hyperswarm and connect multiple process through the topics to broadcast discovering from the webrtc clients.

**Comment by RangerMauve** [comment]
Looking into this now. 😀

**Comment by RangerMauve** [comment]
Question, why are you using your own socket.io thing instead of simple-signal?

**Comment by RangerMauve** [comment]
Regarding the minimal spanning tree method I mentioned on a call before.

When you have a network of peers exchanging data, you ideally don't want them all connecting to each other because having a huge number of connections is taxing on bandwidth and CPU. Ideally, you should have them connected in a [minimum spanning tree](https://en.wikipedia.org/wiki/Minimum_spanning_tree) so that data hops between peers and eventually reaches everyone.

To that end I played around with an algorithm for generating such a tree with a minimal amount of knowledge about other nodes. Here's a live [demo](https://ranger.mauve.moe/graph-mst-viz/) of it in action.

Basically, when a node bootstraps into the network it does the following:

- Gets a random subset of peers (made with the assumption of unreliable discovery through DHTs/MDNS)
- Sorts them by logical distance by XORing peer IDs with it's own. (Based on [Kademlia](https://en.wikipedia.org/wiki/Kademlia) DHTs)
- Tries to connect to it's "closest" peer that it isn't already connected to
- A random subset of peers (I chose 1/3) also connect to their "farthest" peer.

This creates clusters of peers that are "logcally close" to each other, which will randomly reach out to other clusters forming a spanning tree. It's not really a minimal spanning tree, and I'm not a mathematician, but it gets close enough with a fairly simple algorithm.

As you can see in the demo, most nodes end up having two connections, with some having three or four connections. This reduces the load on individual nodes while making sure the swarm is still well connected.

When a peer loses all it's connections, it will perform the same bootstrapping process

You can play around with different percentages and node counts [here](https://github.com/RangerMauve/graph-mst-viz/blob/master/index.html#L33).

**Comment by tinchoz49** [comment]
released new alpha version: `@geut/discovery-swarm-webrtc@2.0.0-alpha.3`

**Comment by tinchoz49** [comment]
New visualization example for the next version using https://github.com/vasturiano/force-graph

![ezgif-3-4b1c8794f893](https://user-images.githubusercontent.com/819446/64871056-d6a2d480-d61a-11e9-9d93-b79a5f0e822a.gif)

**Comment by RangerMauve** [comment]
OMG that's so fancy looking!

**Comment by tinchoz49** [comment]
Yeah :smile: and we also started testing the connectivity of the swarm using ngraph another nice module.

**Comment by tinchoz49** [comment]
closed since v2.0.0 was released
